<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>Welcome to my Fake Website</h1>
            <p>Choose one of the following fake pages:</p>
            <ul class="list-group">
                <li class="list-group-item"><a href="/fake/csrf">CSRF Attack</a></li>
                <li class="list-group-item"><a href="/fake/redirect">OpenRedirect Attack</a></li>
                <li class="list-group-item"><a href="/fake/clickjacking">ClickJacking Attack</a></li>
            </ul>
        </div>
    </div>
</div>