version: '2'

services:
  session:
    image: redis
    ports:
      - '6379:6379'

  database:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: coding
