<?php
/** @var \FW\App\View $this */

$codes = $this->get('codes');
?>
<div class="col-md-10">
    <div class="list-group">
        <?php foreach ($codes as $code): ?>
            <div class="list-group-item">
                <h2><code><?php echo $code[0] ?></code></h2>
                <pre><code><?php echo htmlentities($code[1]) ?></code></pre>
            </div>
        <?php endforeach; ?>
        <div class="list-group-item">
            <h2>Directory Structure</h2>
            <img src="asset/img/app/directory-structure.jpg" class="img-responsive img-rounded">
        </div>
    </div>
</div>
