<?php
/** @var \FW\App\View $this ; */
//$info = $this->get('info');
$info = preg_replace('%^.*<body>(.*)</body>.*$%ms', '$1', $this->get('info'));
?>
<div class="col-md-10">
    <?php echo $info ?>
</div>

<style>
    table {
        width: 90%;
        margin: 5px auto;
        table-layout: fixed;
    }

    th, td {
        padding: 5px 7px;
        font-size: 1em;
        line-height: 1.5;
        vertical-align: middle;
        border: 1px solid grey;
    }

    th {
        background: white;
    }

    .e {
        background: #ccf;
        font-weight: bold;
    }

    .v {
        background: silver;
    }
</style>