<?php
/** @var \FW\App\View $this */
?>

<div id="splash-page">
    <div class="description">
        <code>&lt;?php echo "<span>Secure Coding</span>"; ?&gt;</code>
        <h2>Version: <span>1.0</span></h2>
        <h2>Inspired By:</h2>
        <ul>
            <li><span>DEV522</span> Defending Web Applications Security Essentials</li>
            <li><span>DEV541</span> Secure Coding in Java/JEE: Developing Defensible Applications</li>
            <li><span>DEV544</span> Secure Coding in .NET: Developing Defensible Applications</li>
        </ul>
    </div>
</div>
