<div class="col-md-7">
    <br><br>
    <div class="list-group">
        <div class="list-group-item">Computer Engineering [Hardware] (BSc)</div>
        <div class="list-group-item">Computer Engineering [Software] (MSc)</div>
        <div class="list-group-item">HPC Analyser @MKS International</div>
        <div class="list-group-item">
            Full Stack Web Developer (<code>PHP/Javascript</code>) @[IranWebService, TETA, InfoTec]
        </div>
        <div class="list-group-item">
            Full Stack Web/Hybrid App Developer (<code>NodeJs/Cordova/Electron</code>) @[Vesta Rayan Afzar]
        </div>
        <div class="list-group-item">
            Senior Front-End Developer / Seior DApp Developer (<code>Ethereum</code>)  @[Sadad]
        </div>
        <div class="list-group-item">Developing <code>twilight</code> PHP Framework</div>
        <div class="list-group-item">Developing <code>vesta</code> Platform</div>
        <div class="list-group-item"><a href="https://github.com/VestaRayanAfzar" target="_blank">Open Source Projects</a></div>
    </div>
</div>
