<div class="col-md-7">
    <br><br>
    <div class="list-group">
        <div class="list-group-item active">Expectation</div>
        <div class="list-group-item">Advanced Web Attack Course <span class="badge">Prerequisite</span></div>
        <div class="list-group-item">
            Intermediate level of <code>PHP</code><span class="badge">2 years</span>
        </div>
        <div class="list-group-item">
            Intermediate level of <code>SQL</code><span class="badge">1 year</span>
        </div>
        <div class="list-group-item">
            Design Patterns <span class="badge">MVC, Singleton, Factory, ...</span>
        </div>
        <div class="list-group-item">Have some knowledge about:
            <ul>
                <li>DevOps tools (Vagrant, Docker)</li>
                <li>Web Server (Apache, Nginx, Caddy)</li>
                <li>Client Side build tools (grunt, gulp)</li>
            </ul>
        </div>
        <div class="list-group-item active">A little bit more about you</div>
        <div class="list-group-item">Please introduce yourselves (Education, Occupation, Favorites, ...)</div>
        <div class="list-group-item">Hacked any web site/application?</div>
        <div class="list-group-item">Web Stack Developers? (Raise Hand)</div>
        <div class="list-group-item">Heard of DevOps?</div>
        <div class="list-group-item">Heard of client side build tools?</div>
        <div class="list-group-item">Heard of NoSql databased?</div>
        <div class="list-group-item">More than 5 years of web development?</div>
        <div class="list-group-item">Infrastructure management?</div>
    </div>
</div>