<div class="container">
    <br><br><br>
    <div class="row">
        <div class="col-md-6">
            <fieldset>
                <legend>Sample login</legend>
                <form method="post">
                    <h4>Some real form element...</h4>
                    <br><br>
                    <div class="form-group">
                        <button class="btn btn-primary" name="login" value="1">reLogin</button>
                    </div>
                </form>
            </fieldset>
        </div>
    </div>
</div>