<?php
/** @var \FW\App\View $this */
$file = $this->get('file');
$error = $this->get('error');
?>
<div class="row">
    <fieldset class="col-md-4">
        <legend>Simple File Upload</legend>
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="name">Your Name</label>
                <input type="text" name="name" id="name" value="Test" class="form-control">
            </div>
            <div class="form-group">
                <label for="image">Profile Picture</label>
                <input type="file" name="image" id="image" accept="image/*">
            </div>
            <div class="form-group">
                <button type="submit" name="upload" class="btn btn-primary">Upload Picture</button>
            </div>
        </form>
        <br><br>
        <?php if ($file) {
            echo "<img src='{$file}' class='img-responsive img-thumbnail'/>";
        } elseif ($error) {
            echo "<div class='alert alert-danger'>{$error}</div>";
        } ?>
    </fieldset>
</div>
