<div class="container">
    <div class="row">
        <fieldset class="col-md-6">
            <legend>Terminology</legend>
            <ul class="list-group">
                <li class="list-group-item">Authorization</li>
                <li class="list-group-item">Access Control</li>
                <li class="list-group-item">Where does it sit?</li>
            </ul>
        </fieldset>
    </div>
    <div class="row">
        <fieldset class="col-md-6">
            <legend>Models</legend>
            <ul class="list-group">
                <li class="list-group-item">Permission Based</li>
                <li class="list-group-item">Role-Based Access Control (RBAC)</li>
                <li class="list-group-item">Discretionary Access Control (DAC)</li>
                <li class="list-group-item">Mandatory Access Control (MAC)</li>
            </ul>
        </fieldset>
    </div>
</div>