<div class="row">
    <fieldset class="col-md-6">
        <legend>Defences</legend>
        <div class="list-group">
            <div class="list-group-item">Cross Origin Resource Sharing (CORS)</div>
            <div class="list-group-item">Whitelisting the request sources</div>
            <div class="list-group-item">Same as brute-force mitigation <span class="badge">Already covered</span></div>
            <div class="list-group-item">Same old validating <span class="badge">Already covered</span></div>
        </div>
    </fieldset>
</div>