<div class="container">
    <fieldset class="row">
        <legend>Terminology</legend>
        <ul class="list-group col-md-6">
            <li class="list-group-item">Integrity Check</li>
            <li class="list-group-item">Validation</li>
            <li class="list-group-item">Sanitation (black/white list)</li>
            <li class="list-group-item">Business Rules</li>
        </ul>
        <p>Where is each one of these terms used?</p>
    </fieldset>

    <fieldset class="row">
        <legend>Data Validation Strategies</legend>
        <ul class="list-group col-md-6">
            <li class="list-group-item">Accept known good (whitelist or positive validation)</li>
            <li class="list-group-item">Reject known bad (negative or blacklist validation)</li>
            <li class="list-group-item">Sanitize</li>
            <li class="list-group-item">No validation</li>
        </ul>
    </fieldset>
</div>