<?php
/** @var \FW\App\View $this */
$ciphers = $this->get('ciphers');
?>
<div class="row">
    <fieldset class="col-md-6">
        <div class="list-group">
            <div class="list-group-item">
                <pre>PlainText  --> Encryption [SharedKey] --> CipherText</pre>
            </div>
            <div class="list-group-item">
                <pre>CipherText --> Decryption [SharedKey] --> PlainText</pre>
            </div>
            <div class="list-group-item">What is Initiation Vector(IV)?</div>
        </div>
    </fieldset>
</div>
<div class="row">
    <fieldset class="col-md-6">
        <legend>Symmetric Cryptography</legend>
        <div class="list-group">
            <div class="list-group-item">base on Shared Secret</div>
            <div class="list-group-item">Algorithms:
                <ul>
                    <li>Stream Ciphers</li>
                    <li>Block Ciphers</li>
                </ul>
            </div>
            <div class="list-group-item">
                <strong>Examples</strong>: <code>Twofish</code>, <code>Serpent</code>, <code>AES (Rijndael)</code>,
                <code>RC4</code>, <code>3DES</code>, <code>Skipjack</code>
            </div>
            <div class="list-group-item">
                <code>mcrypt_*</code> is deprecated, instead we should be using <code>openssl_*</code>
            </div>
        </div>
    </fieldset>
</div>
<div class="row">
    <table class="table table-bordered" id="ciphers">
        <tr>
            <th>Method</th>
            <th>IV Length</th>
            <th>Cipher Text</th>
            <th>Plain Text</th>
        </tr>
        <?php foreach ($ciphers as $method => $cipher) {
            echo "<tr><td>{$method}</td><td>{$cipher[0]}</td><td>{$cipher[1]}</td><td>{$cipher[2]}</td></tr>";
        }
        ?>
    </table>
</div>

<style>
    #ciphers {
        width: 90%;
        margin: 10px auto;
    }
</style>