<div class="row">
    <div class="col-md-6">
        <div class="list-group">
            <div class="list-group-item">
                <p>Server side (<code class="inline-code">session_get_cookie_params()</code>):</p>
                <pre><code><?php echo json_encode(session_get_cookie_params(), JSON_PRETTY_PRINT) ?></code></pre>
            </div>
            <div class="list-group-item">
                <p>Server side (<code class="inline-code">$_COOKIE</code>):</p>
                <pre><code><?php echo json_encode($_COOKIE, JSON_PRETTY_PRINT) ?></code></pre>
            </div>
            <div class="list-group-item">
                <p>Client side (<code class="inline-code">document.cookie</code>):</p>
                <pre><code id="cookie-value"></code></pre>
            </div>
        </div>
    </div>
</div>

<script>
    let placeholder = document.getElementById('cookie-value');
    placeholder.textContent = document.cookie.replace(/;\s*/g, '\n');
</script>