<style>
    .headers-list li > span:first-child {
        display: inline-block;
        width: 200px;
        font-weight: bold;
        white-space: nowrap;
    }
</style>

<div class="container">
    <ul id="placeholder" class="headers-list"></ul>
</div>

<script>
    let placeholder = document.getElementById('placeholder');
    fetch(location.href)
        .then(response => {
            let headers = response.headers.keys();
            let html = '';
            for (let header of headers) {
                html += `<li><span>${header}</span><span>${response.headers.get(header)}</span></li>`;
            }
            placeholder.innerHTML = html;
        })
</script>