<?php
/** @var \FW\App\View $this */
$action = $this->get('action');
$message = $this->get('message');
?>
<div class="row">
    <form class="col-sm-4" action="<?php echo $action ?>" method="post">
        <?php if ($message) echo "<div class='alert alert-success'>{$message}</div>"; ?>
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-danger">Delete User</button>
        </div>
    </form>
</div>
<br><br>
<div class="row">
    <a href="http://fake.io/fake/csrf" class="btn" target="_blank">Fake Website</a>
</div>
<br><br>
