<div class="row">
    <fieldset class="col-md-6">
        <legend>Attacks and Vulnerabilities</legend>
        <div class="list-group">
            <div class="list-group-item">XMLHttpRequest Vulnerabilities</div>
            <div class="list-group-item">Increased Attack Surface</div>
            <div class="list-group-item">SQL Injection</div>
            <div class="list-group-item">Cross Site Request Forgery (CSRF)</div>
            <div class="list-group-item">DOS</div>
        </div>
    </fieldset>
</div>