<div class="row">
    <fieldset class="col-md-6">
        <legend>Types of attacks</legend>
        <div class="list-group">
            <div class="list-group-item">Injection [XSS (Reflected/DOM-Based, Stored), SQL]</div>
            <div class="list-group-item">Depth Attack</div>
            <div class="list-group-item">Width Attack</div>
            <div class="list-group-item">Looping Attack</div>
            <div class="list-group-item">RCE Attack</div>
            <div class="list-group-item">Any mitigation suggestion?</div>
        </div>
    </fieldset>
</div>