<div class="container">
    <fieldset class="col-sm-4">
        <form action="?controller=chapter2&code=24" method="post">
            <div class="form-group">
                <div class="input-group">
                    <label for="password">Password</label>
                    <input type="text" name="password" id="password" class="form-control">
                </div>
            </div>
            <div class="input-group" id="progress">
                <button class="btn btn-primary" name="submit" value="1">Submit</button>
            </div>
        </form>
    </fieldset>
</div>
