<?php
/** @var \FW\App\View $this */
$action = $this->get('action');
$message = $this->get('message');
?>
<div class="row">
    <div class="col-md-7">
        <p>Cookie of this domain (<span class="inline-code">document.cookie</span>):</p>
        <pre><code id="placeholder"></code></pre>
    </div>
</div>
<br><br>
<div class="row">
    <form class="col-md-6" action="<?php echo $action ?>" method="post">
        <?php if ($message) echo "<div class='alert alert-success'>{$message}</div>"; ?>
        <input type="hidden" name="csrf-token" value="<?php echo $this->get('csrf-token') ?>">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-danger">Delete User</button>
        </div>
    </form>
</div>
<br><br>

<script>
    document.getElementById('placeholder').textContent = document.cookie.split(/;\s*/).join('\n');
</script>
