<div class="container">
    <h2 class="alert alert-info col-md-10 col-md-offset-1">Same as RBAC (Role ~= User)</h2>
    <div class="row">
        <fieldset class="col-md-6">
            <legend class="text-success">Advantages:</legend>
            <div class="list-group">
                <div class="list-group-item">Easy to understand</div>
                <div class="list-group-item">Easy to use</div>
            </div>
        </fieldset>
    </div>
    <div class="row">
        <fieldset class="col-md-6">
            <legend class="text-danger">Disadvantages:</legend>
            <div class="list-group-item">Hard to administer</div>
            <div class="list-group-item">Assigning/Revoking roles</div>
        </fieldset>
    </div>
</div>