<div class="container">
    <p class="alert alert-info col-md-10 col-md-offset-1">
        Enforcement of organizational security policy does not rely on voluntary web application user compliance
        <br><br>
        <span>e.g. extremely secure systems<strong class="text-danger">(Military Applications)</strong></span>
    </p>
    <div class="row">
        <fieldset class="col-md-6">
            <legend class="text-success">Advantages:</legend>
            <div class="list-group">
                <div class="list-group-item">Access to an object is based on the sensitivity of the object</div>
                <div class="list-group-item">Only an administrator can grant access</div>
            </div>
        </fieldset>
    </div>
    <div class="row">
        <fieldset class="col-md-6">
            <legend class="text-danger">Disadvantages:</legend>
            <div class="list-group-item">Difficult and expensive to implement</div>
            <div class="list-group-item">Not agile</div>
            <div class="list-group-item">Only an administrator can grant access</div>
        </fieldset>
    </div>
</div>