<?php include __DIR__ . "/code16.phtml"; ?>

<div class="row">
    <div class="col-md-6">
        <p><code class="inline-code">ServerTokens</code></p>
        <ul class="headers-list list-group">
            <li class="list-group-item"><span>Full</span><span>Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.1</span></li>
            <li class="list-group-item"><span>OS</span><span>Apache/2.4.25 (Win32)</span></li>
            <li class="list-group-item"><span>Minimal</span><span>Apache/2.4.25</span></li>
            <li class="list-group-item"><span>Minor</span><span>Apache/2.4</span></li>
            <li class="list-group-item"><span>Major</span><span>Apache/2</span></li>
            <li class="list-group-item"><span>Prod</span><span>Apache</span></li>
        </ul>
    </div>
</div>