<div class="container">
    <p class="alert alert-info col-md-10 col-md-offset-1">
        Restricting access to information based on the identity of users and/or membership in certain groups
        <br><br><span class="text-danger">e.g. <strong>Facebook PARSE</strong></span>
    </p>
    <div class="row">
        <fieldset class="col-md-6">
            <legend class="text-success">Advantages:</legend>
            <div class="list-group">
                <div class="list-group-item">Easy to use</div>
                <div class="list-group-item">Easy to administer</div>
                <div class="list-group-item">Object owner has total control over access granted</div>
            </div>
        </fieldset>
    </div>
    <div class="row">
        <fieldset class="col-md-6">
            <legend class="text-danger">Disadvantages:</legend>
            <div class="list-group-item">Hard to implement (Needs extra fields)</div>
            <div class="list-group-item">Data Based Access Control</div>
        </fieldset>
    </div>
</div>