<?php
/** @var \FW\App\View $this */
$error = $this->get('error');
$user = $this->get('user');
?>
<div class="container">
    <?php if (!$user || $error): ?>
        <fieldset class="col-sm-6">
            <legend>User Login Form</legend>
            <?php echo $error ? "<p class='alert alert-danger'>{$error}</p>" : '' ?>
            <form name="loginForm" action="?controller=chapter2&code=21" method="post">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username" class="form-control">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password" class="form-control">
                </div>
                <div class="form-group text-right">
                    <button type="submit" class="btn btn-primary" name="login" value="1">Login</button>
                    <button type="reset" class="btn btn-default">Reset</button>
                </div>
            </form>
        </fieldset>
    <?php elseif ($user): ?>
        <h1>Welcome <?php echo $user['username'] ?></h1>
        <form action="?controller=chapter2&code=21" method="post">
            <button type="submit" name="logout" value="1" class="btn btn-danger">Logout</button>
        </form>
    <?php endif; ?>
</div>

<script>
    let form = document.querySelector('form[name=loginForm]');
    let userInput = document.getElementById('username');
    let passInput = document.getElementById('password');
    form.addEventListener('submit', event => {
        let username = userInput.value;
        let password = passInput.value;
        userInput.parentElement.classList.remove('has-error');
        passInput.parentElement.classList.remove('has-error');
        let isValid = true;
        if (8 < username.length || username.length < 4 || !/^\w[\w\d]+$/i.exec(username)) {
            isValid = false;
            userInput.parentElement.classList.add('has-error');
        }
        if (10 < password.length || password.length < 5) {
            isValid = false;
            passInput.parentElement.classList.add('has-error');
        }
        if (!isValid) {
            event.preventDefault();
            return false;
        }
    }, false);
</script>