<?php include __DIR__ . "/code16.phtml"; ?>

<div class="container">
    <p><code class="inline-code">ServerTokens</code></p>
    <ul class="headers-list">
        <li><span>Full</span><span>Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.1</span></li>
        <li><span>OS</span><span>Apache/2.4.25 (Win32)</span></li>
        <li><span>Minimal</span><span>Apache/2.4.25</span></li>
        <li><span>Minor</span><span>Apache/2.4</span></li>
        <li><span>Major</span><span>Apache/2</span></li>
        <li><span>Prod</span><span>Apache</span></li>
    </ul>
</div>