<?php
/** @var \FW\App\View $this */
$block = $this->get('theme');
?>
<div class="container">
    <fieldset class="col-sm-2">
        <form action="?controller=chapter5&code=46" method="post" name="pingForm">
            <div class="form-group">
                <label for="theme">Theme</label>
                <select name="theme" id="theme" class="form-control">
                    <option value="dark">Dark</option>
                    <option value="light">Light</option>
                </select>
            </div>
            <div class="form-group">
                <button type="submit" name="apply" class="btn btn-primary">Apply Theme</button>
            </div>
            <div class="form-group">
                <?php echo $block; ?>
            </div>
        </form>
    </fieldset>
</div>
