<div class="row">
    <fieldset class="col-md-6">
        <legend>A little bit of history</legend>
        <div class="list-group">
            <div class="list-group-item">Asynchronous Javascript And Xml</div>
            <div class="list-group-item">Web applications can send/retrieve data to/from server asynchronously</div>
            <div class="list-group-item">
                In <strong>1996</strong>, the iframe tag was introduced by Internet Explorer to load or to fetch content
                asynchronously
            </div>
            <div class="list-group-item">
                In <strong>1998</strong>, Microsoft Outlook Web App team implemented the first component XMLHTTP by
                client script
            </div>
            <div class="list-group-item">
                In <strong>1999</strong>, Microsoft created XMLHTTP ActiveX control in Internet Explorer 5 [followed by
                Mozilla, Safari, Firefox]
            </div>
            <div class="list-group-item">
                In <strong>2004</strong>, Google widely used this technology for Gmail [and in 2005, for Google Maps]
            </div>
            <div class="list-group-item">
                On 5 April <strong>2006</strong>, the World Wide Web Consortium (W3C) released the first draft
            </div>
        </div>
    </fieldset>
</div>

<div class="row">
    <fieldset class="col-md-6">
        <legend>Technologies</legend>
        <div class="list-group">
            <div class="list-group-item">HTML (or XHTML) and CSS for presentation</div>
            <div class="list-group-item">The DOM for dynamic display of and interaction with data</div>
            <div class="list-group-item">JSON or XML for the interchange of data</div>
            <div class="list-group-item">The XMLHttpRequest object for asynchronous communication</div>
            <div class="list-group-item">JavaScript to bring these technologies together</div>
        </div>
    </fieldset>
</div>