<?php
/** @var \FW\App\View $this */
$formAction = $this->get('form');
?>
<div class="row">
    <fieldset class="col-sm-4">
        <form action="<?php echo $formAction ?>" method="post">
            <div class="form-group">
                <div class="input-group">
                    <label for="password">Password</label>
                    <input type="text" name="password" id="password" class="form-control">
                </div>
            </div>
            <div class="input-group" id="progress">
                <button class="btn btn-primary" name="submit" value="1">Submit</button>
            </div>
        </form>
    </fieldset>
</div>
