<div class="container">
    <div class="row">
        <fieldset class="col-md-6">
            <div class="list-group">
                <div class="list-group-item">
                    <pre>PlainText  --> Encryption --> CipherText</pre>
                </div>
                <div class="list-group-item">
                    <pre>CipherText --> Decryption --> PlainText</pre>
                </div>
                <div class="list-group-item">What is Initiation Vector(IV)?</div>
            </div>
        </fieldset>
    </div>
    <div class="row">
        <fieldset class="col-md-6">
            <legend>Symmetric-key algorithm</legend>
            <div class="list-group">
                <div class="list-group-item">base on Shared Secret</div>
                <div class="list-group-item">Algorithms:
                    <ul>
                        <li>Stream Ciphers</li>
                        <li>Block Ciphers</li>
                    </ul>
                </div>
                <div class="list-group-item">
                    Twofish, Serpent, AES (Rijndael), RC4, 3DES, Skipjack, IDEA
                </div>
            </div>
        </fieldset>
    </div>
</div>