<div class="container">
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item">The same as previous lesson</li>
                <li class="list-group-item">Do NOT use direct link to file</li>
                <li class="list-group-item">Do NOT use simple file name</li>
                <li class="list-group-item"><pre><code>&lt;a href="/files/answers.pdf">All answers&lt;/a></code></pre></li>
                <li class="list-group-item">Use Obfuscation & Random file name</li>
                <li class="list-group-item"><pre><code>&lt;a href="/files?file=123">All answers&lt;/a></code></pre></li>
            </ul>
        </div>
    </div>
</div>