<div class="container">
    <div class="row">
        <fieldset class="col-md-6">
            <legend>Definition</legend>
            <div class="list-group">
                <div class="list-group-item">What is Web Service?</div>
                <div class="list-group-item">Why do we use Web Services?</div>
                <div class="list-group-item">How does it work?</div>
            </div>
        </fieldset>
    </div>
    <div class="row">
        <fieldset class="col-md-6">
            <legend class="text-danger">VERY dangerous, but common assumptions</legend>
            <div class="list-group">
                <div class="list-group-item">The client is 100% trusted</div>
                <div class="list-group-item">The data is secure and doesn't need validation</div>
                <div class="list-group-item">Since they don't have UIs, they are NOT discoverable</div>
            </div>
        </fieldset>
    </div>
    <div class="row">
        <fieldset class="col-md-6">
            <legend>The most IMPORTANT advice</legend>
            <div class="alert alert-danger">NEVER EVER NEVER stop validating received data EVER</div>
        </fieldset>
    </div>
</div>