<?php
/** @var \FW\App\View $this */
$serverCode = $this->get('serverCode');
$clientCode = \FW\Util\Util::removeTag($this->get('clientCode'), 'style');
$link = $this->get('link');
$next = $this->get('next');
$prev = $this->get('prev');
?>
<ol class="breadcrumb main-breadcrumb">
    <li><?php echo $this->get('h1') ?></li>
    <li><?php echo $this->get('h2') ?></li>
</ol>
<div class="container">
    <div class="navigation btn-group">
        <?php echo $prev ? "<a href='{$prev}' id='prev-btn' class='btn glyphicon glyphicon-chevron-left' title='Previous'></a>" : '' ?>
        <a href="/index/heading" id="home-btn" class="btn glyphicon glyphicon-home" title="Home"></a>
        <?php echo $next ? "<a href='{$next}' id='next-btn' class='btn glyphicon glyphicon-chevron-right' title='Next'></a>" : '' ?>
        <a class="btn glyphicon glyphicon-barcode" id="toggle" title="Toggle Code"></a>
    </div>
    <div class="row">
        <?php if ($link) {
            echo "<h3>Helpful Links:</h3><ul class='links'>";
            if (is_array($link)) {
                foreach ($link as $item) {
                    echo "<li><a target='_blank' href='{$item[1]}'>{$item[0]}</a></li>";
                }
            }
            echo '</ul>';
        } ?>
    </div>
    <div class="row">
        <div class="playground collapsed">
            <?php if ($serverCode) echo "<h3>Server</h3><pre><code>$serverCode</code></pre>" ?>
            <?php if ($clientCode) echo "<h3>Client</h3><pre><code>$clientCode</code></pre>" ?>
        </div>
        <div class="result">
            <?php echo $this->get('result') ?>
        </div>
    </div>
</div>

<script>
    hljs.initHighlightingOnLoad();
    let toggle = document.getElementById('toggle');
    let playground = document.querySelector('.playground');
    toggle.addEventListener('click', () => {
        let className = 'collapsed';
        if (playground.classList.contains(className)) {
            playground.classList.remove(className);
        } else {
            playground.classList.add(className);
        }
    });
    // next
    document.addEventListener('keydown', e => {
        if (e.target.tagName.toLowerCase() === 'input') return false;
        if (e.keyCode === 39) {
            // right
            let next = document.getElementById('next-btn');
            next ? window.location.href = next.getAttribute('href') : goHome();
        } else if (e.keyCode === 37) {
            // left
            let prev = document.getElementById('prev-btn');
            prev ? window.location.href = prev.getAttribute('href') : goHome();
        }
        function goHome() {
            window.location.href = document.getElementById('home-btn').getAttribute('href');
        }
    }, false);
</script>