<?php
/** @var \FW\App\View $this */
$headings = $this->get('headings');
?>
<div class="page">
    <h1>Topics</h1>
    <div class="page" id="headings-page">
        <ol>
            <?php foreach ($headings as $heading) {
                echo "<li id='chapter{$heading['id']}'>{$heading['title']}<ol>";
                foreach ($heading['children'] as $child) {
                    $link = "/chapter{$heading['id']}?code=${child['id']}";
                    echo "<li><a href='{$link}'>{$child['title']}</a></li>";
                }
                echo '</ol></li>';
            }
            ?>
        </ol>
    </div>
</div>
